name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'

      - name: Build
        run: go build

      - name: Check Test Tokens not expired
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FERMYBOT_FWF_TEST_TOKEN: ${{ secrets.FERMYBOT_FWF_TEST_TOKEN }}
        run: |
          ./auth-token-monitor --token-env-vars TEST_TOKEN,GITHUB_TOKEN --expiration-threshold=0
          ./auth-token-monitor --token-env-vars FERMYBOT_FWF_TEST_TOKEN --expiration-threshold=0 --provider fwf

      - name: Check Test Token expiring in next year
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: |
          set +e
          ./auth-token-monitor --token-env-vars TEST_TOKEN --expiration-threshold=262800h
          code=$?
          set -e
          if [ "${code}" -ne "1" ]; then
            echo "Expected exit code 1, got ${code}"
            exit 10
          fi

      - name: Check Test Tokens not expiring soon (need to be rotated)
        continue-on-error: true
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          FERMYBOT_FWF_TEST_TOKEN: ${{ secrets.FERMYBOT_FWF_TEST_TOKEN }}
        run: |
          ./auth-token-monitor --token-env-vars TEST_TOKEN --expiration-threshold=720h
          ./auth-token-monitor --token-env-vars FERMYBOT_FWF_TEST_TOKEN --expiration-threshold=720h --provider fwf
